version: "3.9"

services:
  db:
    container_name: postgres
    image: postgres:13.6-alpine
    environment:
      - POSTGRES_DB=hr
      - POSTGRES_USER=hr
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
